services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
    command: ["--log_bin_trust_function_creators=1"]
  app:
    container_name: kf2-stats-backend
    init: true
    build:
      context: .
      dockerfile: docker/migration/Dockerfile
    env_file:
      - .env
    environment:
      - DB_PATH=/mnt/store/store.sqlite
      - DB_HOST=db
      - GOPATH=/code/.go
    ports:
      - '3000:3000/tcp'
    depends_on:
      - db
    links:
      - "db:database"
    working_dir: /code
    volumes:
      - sqlite-db:/mnt/store
volumes:
  sqlite-db:
  mysql-data:
